#!/usr/bin/env perl
use 5.014;
use warnings;
use utf8;

my @files = grep {/\.go$/} grep {chomp && /\.go$/} `git ls-files --others; git diff --name-only --relative --diff-filter=AM`;
exec('lazy-goimports', @files);
